### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Pdzly** [WilliamVenner/gmsv_workshop#1]
This is just for the SAME thing as clientside but serverside

**Comment by WilliamVenner** [comment]
steamworks.DownloadUGC and steamworks.FileInfo are clientside functions. This brings them to the server for runtime Workshop addon downloading and mounting.

**Comment by Pdzly** [comment]
Would it be then so possible like: I want for example M9K weapons on my serrver and it loads and mounts that would be there lag or is it possible for that to show the weapons after that mounted? or is it just for matterial or so?

**Comment by WilliamVenner** [comment]
No that is unnecessary. My use case for this module is letting players load their custom playermodels on my personal TTT server. This could also be used by scripts like https://www.gmodstore.com/market/view/xenin-custom-jobs-creator
