### ISSUE TITLE
Why file_class in DownloadUGC always equals `false` ?

### ISSUE THREAD

**Issue by unknown-gd** [WilliamVenner/gmsv_workshop#2]
If it's possible could you fix this and return `file_class` in `DownloadUGC` to work with...

**Comment by WilliamVenner** [comment]
Are you up to date? I believe I fixed this in the latest version.

**Comment by unknown-gd** [comment]
oh, I checked right now, yes the version is the latest, but a new problem has appeared, on win64 instead of path UGC returns nil

**Comment by unknown-gd** [comment]
it happens with legacy addons

**Comment by unknown-gd** [comment]
oh no, it happens with any addons

**Comment by WilliamVenner** [comment]
Please show your code. It is working fine for me on Windows x86-64

**Comment by WilliamVenner** [comment]
I believe the bug has been fixed in v2.2.0

**Comment by PrikolMen** [comment]
https://github.com/Pika-Software/addon_util

**Comment by unknown-gd** [comment]
yes it's fixed in v2.2.0
