### ISSUE TITLE
Couldn't load module library!

### ISSUE THREAD

**Issue by selenter-c** [WilliamVenner/gmsv_workshop#5]
Hello! I have a problem connecting the library to my server. "require" raises an error. Checked on x32 versions, on Windows and Linux Ubuntu.

Screenshots of errors:
![image](https://user-images.githubusercontent.com/49411627/158626782-7338023e-6926-464b-a64b-d841c5253509.png)
![image](https://user-images.githubusercontent.com/49411627/158626804-bd9a134f-742b-46a1-ae34-77550706beb4.png)

Can you suggest what is the problem? Looks like there's an update to steamworks.

**Comment by WilliamVenner** [comment]
Fixed in 2.2.4, you'll need to update your Gmod server too, thank you

**Comment by FlorianLeChat** [comment]
Looks like GitHub failed during the creation of the Linux versions

**Comment by selenter-c** [comment]
> Fixed in 2.2.4, you'll need to update your Gmod server too, thank you

thx

**Comment by WilliamVenner** [comment]
> Looks like GitHub failed during the creation of the Linux versions

thanks, I forgot to do something :D
