### ISSUE TITLE
undefined symbol: SteamAPI_SteamGameServer_v013

### ISSUE THREAD

**Issue by justinkluever** [WilliamVenner/gmsv_workshop#7]
Couldn't load module library! (/home/container/garrysmod/lua/bin/gmsv_workshop_linux.dll: undefined symbol: SteamAPI_SteamGameServer_v013)

seems like the steamworks update broke it :/

**Comment by WilliamVenner** [comment]
Give v2.2.5 a try

**Comment by justinkluever** [comment]
I'm getting no more errors with v2.2.5 so it should be fixed now, thanks!
